### ISSUE TITLE
Other environment requirements |  WiKi Link Broken

### ISSUE THREAD

**Issue by secabhk001** [ryanlayerlab/TEPEAK#10]
Hi,
I have installed TEPEAK. However, I would like to know how I can install NCBI SDK?  The WiKi Link  (https://github.com/ryanlayer/TEPEAK/wiki/Species-Name-and-SRA-List-Startup) seems to be broken.
Could you kindly provide a working link? 

Thanks,
Abhishek

**Comment by mrburke00** [comment]
Try this link instead  

https://github.com/ryanlayerlab/TEPEAK/wiki/Installing-NCBI-SDK-and-Picard
